apiVersion: v1
kind: Service
metadata:
  name: opensearch-exporter-service
  namespace: mantis-system
spec:
  selector:
    app: opensearch-exporter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31000
  type: NodePort
